In [1]:
import pandas as pd

In [8]:
violation_df = pd.read_csv('Data/Property_Standards_Violations_2_Cleaned.csv')
pd.set_option('display.max_columns', None)

/var/folders/5y/6gtz4tzx39g7849gcdbdht800000gp/T/ipykernel_99569/2744169512.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  violation_df = pd.read_csv('Data/Property_Standards_Violations_2_Cleaned.csv')

In [12]:
permits_df = pd.read_csv('Data/Building_Permits_Issued_Cleaned.csv')
pd.set_option('display.max_columns', None)

In [13]:
violation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42716 entries, 0 to 42715
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   object_id            42716 non-null  int64
 1   request_#            42716 non-null  object
 2   date_received        42716 non-null  object
 3   property_apn         42716 non-null  object
 4   property_address     42716 non-null  object
 5   city                 42713 non-null  object
 6   state                42716 non-null  object
 7   property_owner       42716 non-null  object
 8   complaint_source     42716 non-null  object
 9   reported_problem     42716 non-null  object
 10  status               42716 non-null  object
 11  cncl_dist            42716 non-null  int64
 12  last_activity_date   42709 non-null  object
 13  Last_Activity        42709 non-null  object
 14  last_act__result     42709 non-null  object
 15  violations_noted     42667 non-null  object
 16  longitude            42716 non-null  float64
 17  latitude             42716 non-null  float64
 18  zipcode              42716 non-null  int64
 19  subtype_description  42716 non-null  object
 20  x                    42716 non-null  float64
 21  y                    42716 non-null  float64
dtypes: float64(4), int64(3), object(15)
memory usage: 7.2+ MB

In [14]:
permits_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28622 entries, 0 to 28621
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Permit_#                    28622 non-null  object
 1   Permit_type_description     28622 non-null  object
 2   Permit_subtype_description  28622 non-null  object
 3   Parcel                      28622 non-null  object
 4   Date_entered                28622 non-null  object
 5   Date_issued                 28622 non-null  object
 6   Construction_cost           28622 non-null  int64
 7   Address                     28622 non-null  object
 8   City                        28620 non-null  object
 9   State                       28622 non-null  object
 10  Subdivision_lot             28622 non-null  object
 11  Contact                     28621 non-null  object
 12  Permit_type                 28622 non-null  object
 13  Permit_sub_type             28622 non-null  object
 14  Purpose                     28622 non-null  object
 15  Council_district            28607 non-null  float64
 16  Census_tract                28622 non-null  int64
 17  Longitude                   28622 non-null  float64
 18  Latitude                    28622 non-null  float64
 19  ObjectId                    28622 non-null  int64
 20  Zipcode                     28622 non-null  int64
 21  x                           28622 non-null  float64
 22  y                           28622 non-null  float64
dtypes: float64(5), int64(4), object(14)
memory usage: 5.0+ MB

In [37]:
permits_df.head(25)

,Permit_#,Permit_type_description,Permit_subtype_description,Parcel,Date_entered,Date_issued,Construction_cost,Address,City,State,Subdivision_lot,Contact,Permit_type,Permit_sub_type,Purpose,Council_district,Census_tract,Longitude,Latitude,ObjectId,Zipcode,x,y
0,2020037584,Building Commercial - Rehab,Day Care Center (Up To 75) - Child Care,5106006200,6/17/2020,4/9/2024,82455,1022 S GRAYCROFT AVE,MADISON,TN,LOT 1 DUE WEST TOWERS DAY CARE,TANDEM CONSTRUCTION LLC,CACR,CAB03I402,parcel is zoned RM9 and RS20 and contains 11.1...,3.0,37010802,-86.736233,36.252179,1,37115,-9655433.269,4335376.492
1,2020062603,Building Use & Occupancy,"Multifamily, Townhome",4315005700,10/5/2020,7/24/2023,1,910 OLD HICKORY BLVD E,MADISON,TN,LOT 60 SEC 2 A RAINBOW TERRACE,JARRATT BUILDERS LLC,CAUO,CAA03R301,MASTER PERMIT ONLY… … NO CONSTRUCTION… …OLD HI...,9.0,37010602,-86.689794,36.262452,2,37115,-9650263.708,4336794.677
2,2020077789,Building Commercial - New,Restaurant (Take Out),7102009200,12/14/2020,9/26/2023,409214,2505 BRICK CHURCH PIKE,NASHVILLE,TN,E SIDE BRICK CH PK N OF BROOKLYN AVE,VIVID1 BUILDERS LLC,CACN,CAF31A203,retail market with take out food 1 story with ...,2.0,37012701,-86.778860,36.212955,3,37207,-9660178.492,4329963.316
3,2021020545,Building Commercial - New,"Community Education, Indr Tennis Court",13114010000,4/6/2021,11/7/2023,1,1313 HILDRETH DR,NASHVILLE,TN,LOT 316 & 317 SEC 8 SEVEN HILLS,Seven Hill Club,CACN,CAC03A313,Use permit to erect a bubble over existing ten...,34.0,37018602,-86.813901,36.082376,4,37215,-9664079.235,4311962.049
4,2021023674,Building Commercial - New,"Leasing / Sales Office, Other",16400033500,4/18/2021,1/30/2024,10000,110 WATERSTONE WAY 1412,ANTIOCH,TN,LOT 2 3300 MURFREESBORO PIKE,CIP CONSTRUCTION COMPANY,CACN,CAD03B000,To construct a 50 sf mail kiosk for Cascades A...,8.0,37015631,-86.618345,36.060232,6,37013,-9642310.087,4308912.433
5,T2021027879,Building Residential - New,"Accessory Structure, Pools - Residential",13004001000,5/4/2021,4/7/2026,1638305,4024 B SUNNYBROOK DR,NASHVILLE,TN,LOT 18 PT 17 ROYAL OAKS,WIECK CONSTRUCTION LLC,CARN,CAA14U017,"Addition of a new Pool House, Patios and swimm...",34.0,37017902,-86.842535,36.098825,28617,37205,-9667266.791,4314228.085
6,2021035334,Building Residential - New,Single Family Residence,160080C00700CO,6/6/2021,8/28/2025,406275,5412 TROUSDALE DR,NASHVILLE,TN,LOT 7 BRENTWOOD BRANCH,RAD DEVELOPMENT INC,CARN,CAA01R301,new build - residence 3351 H&C square feet....,26.0,37018801,-86.757758,36.050057,5,37220,-9657829.434,4307511.344
7,2021036500,Building Demolition Permit,Demolition Permit - Residential,8507004400,6/10/2021,11/7/2023,2500,3132 EDGEMONT DR,NASHVILLE,TN,"LOT 213 SEC 4, STANFORD COUNTRY CLUB ESTATES",PRECISION CONSTRUCTION COMPANY,CADM,CAZ01A001,Demolition has already taken place and a new s...,14.0,37015501,-86.645028,36.183770,7,37214,-9645280.381,4325937.419
8,2021037636,Building Commercial - Tenant Finish Out,"Multifamily, Apt / Twnhome > 5 Unit Bldg",105071C00100CO,6/15/2021,9/15/2023,40000,624 MERRITT ST 101,NASHVILLE,TN,UNIT 4 THE FINERY MASTER CONDOMINIUM AMENDED,ARCHER WESTERN CONSTRUCTION LLC,CACT,CAA03R399,BUILDING PERMIT #2: FLEX SPACE within THE FINE...,17.0,37016100,-86.770966,36.140038,8,37203,-9659299.727,4319907.562
9,2021038553,Building Commercial - Tenant Finish Out,"Multifamily, Apt / Twnhome > 5 Unit Bldg",105071C00100CO,6/18/2021,9/15/2023,40000,620 MERRITT AVE 101,NASHVILLE,TN,UNIT 4 THE FINERY MASTER CONDOMINIUM AMENDED,ARCHER WESTERN CONSTRUCTION LLC,CACT,CAA03R399,BUILDING PERMIT #6: FLEX SPACE WHITE BOX with...,17.0,37016100,-86.770210,36.139994,9,37203,-9659215.545,4319901.429
10,2021038554,Building Commercial - Tenant Finish Out,"Multifamily, Apt / Twnhome > 5 Unit Bldg",105071C00100CO,6/18/2021,10/6/2023,40000,475 GRAY ST,NASHVILLE,TN,UNIT 4 THE FINERY MASTER CONDOMINIUM AMENDED,ARCHER WESTERN CONSTRUCTION LLC,CACT,CAA03R399,BUILDING PERMIT #25: Flex Space North WHITE BO...,17.0,37016100,-86.770199,36.141129,10,37203,-9659214.378,4320057.923
11,2021043334,Building Sign Permit,Sign - Ground / Wall Signs,10606007300,7/9/2021,10/19/2023,20000,630 MURFREESBORO PIKE,NASHVILLE,TN,LOT 2 JOSLIN SIGN COMMERCIAL SUB.,JOSLIN SIGN & MAINTENANCE CO INC,CASN,CAZ02A001,to remove existing and erect 58Sf illuminated ...,16.0,37015900,-86.738868,36.141272,11,37210,-9655726.647,4320077.603
12,2021047790,Building Residential - New,Detached Accessory Dwelling Unit,11704025400,7/28/2021,11/30/2023,450000,2804 B OAKLAND AVE,NASHVILLE,TN,LOT 33 BELMONT TERRACE,LAYTON HOMES 2 LLC,CARN,CAA11R301,RECEIVED DETACHED DWELLING COVENANT 20210813-0...,18.0,37016900,-86.795751,36.122052,12,37212,-9662058.795,4317428.549
13,2021049445,Building Commercial - New,Recycling Facility,4303001000,8/4/2021,4/8/2024,1057200,928 MYATT INDUSTRIAL DR,MADISON,TN,LOT 10 RIVERGATE INDUSTRIAL PARK,Dave Purser,CACN,CAK05H000,"Construct an approx. 10,700 sqft engineered me...",9.0,37010401,-86.688659,36.280431,13,37115,-9650137.406,4339277.182
14,2021056442,Building Use & Occupancy,"Multifamily, Townhome",10505035500,9/1/2021,2/15/2024,1,1605 B HILLSIDE AVE,NASHVILLE,TN,LOT 3 PARK AT HILLSIDE EDGEHILL ESTATES RESUB,JOHN PATTERSON,CAUO,CAA03R301,MASTER PERMIT NO CONSTRUCTION THIS PERMIT for ...,17.0,37016200,-86.783785,36.138100,15,37203,-9660726.764,4319640.448
15,2021057128,Building Use & Occupancy,Master Permit Application,9410000200,9/3/2021,8/14/2023,1,925 LEBANON PIKE,NASHVILLE,TN,LOT 1 W.M. OMOHUNDROS SUB,Marcus Hammonds 618-979-9569,CAUO,CAZ03A001,"BZA Order 2021-141 granted, 5,464 sq ft mini m...",15.0,37019600,-86.740801,36.153929,14,37210,-9655941.749,4321822.440
16,2021061942,Building Commercial - Shell,"Multifamily, Townhome",9212046900,9/27/2021,1/9/2025,80212214,1717 HAYES ST,NASHVILLE,TN,PT OF LOT 72-77 BOYD HOME TRACT,JUSTIN CRANDALL,CACH,CAA03R301,This is a Core & Shell permit package for a hi...,19.0,37019500,-86.796363,36.154097,16,37203,-9662126.966,4321845.628
17,2021063222,Building Commercial - New,"Fuel Storage, Hazardous (H1-H5)",9209017700,10/1/2021,2/21/2024,7500000,416 38TH AVE N,NASHVILLE,TN,LOTS 22 TH 25 & 42 TH 45 W. R. WILSON,PAULO FONDA,CACN,CAH03H000,Construction of a new 2.5 million gallon groun...,24.0,37013500,-86.829826,36.153903,17,37209,-9665852.028,4321818.852
18,2021065100,Building Residential - New,Single Family Residence,160080C00500CO,10/11/2021,2/23/2024,425272,5421 TROUSDALE DR,NASHVILLE,TN,LOT 5 BRENTWOOD BRANCH,RAD DEVELOPMENT INC,CARN,CAA01R301,TO CONSTRUCT SINGLE FAMILY RESIDENCE WITH 3234...,26.0,37018801,-86.757718,36.049594,18,37220,-9657825.020,4307447.550
19,2021068296,Building Residential - New,"Accessory Structure, Pools - Residential",062110B01600CO,10/25/2021,9/7/2023,92000,2707 B PENNINGTON BEND RD,NASHVILLE,TN,LOT 16 THE SUMMIT AT PENNINGTON BEND CHASE,BACKYARD LIVING LLC,CARN,CAA14U017,TO INSTALL 14’X22’ INGROUND POOL TO REAR OF EX...,15.0,37015300,-86.688073,36.224199,19,37214,-9650072.153,4331514.823
20,2021072100,Building Use & Occupancy,Master Permit Application,103024C90000CO,11/9/2021,4/28/2025,1,249 B WHITE BRIDGE PIKE,NASHVILLE,TN,COMMON AREA HOMES AT 247-249 WHITE BRIDGE PIKE,Derek Wilson,CAUO,CAZ03A001,3 building 14 unit residential condominium dev...,20.0,37018101,-86.858053,36.141830,22,37209,-9668994.178,4320154.552
21,2021072903,Building Commercial - New,"Religious Institution, Worship Space",17400009100,11/12/2021,9/18/2023,749742,5736 CANE RIDGE RD,ANTIOCH,TN,E/S CANE RIDGE RD S OF OLD FRANKLIN RD,Dave Purser,CACN,CAB10A305,"Construct a one-story 4,500 SF sanctuary. Mini...",33.0,37019117,-86.642705,36.020986,20,37013,-9645021.795,4303509.374
22,2021078543,Building Commercial - Tenant Finish Out,Hotel / Motel,9314056500,12/8/2021,8/29/2023,6872557,920 DIVISION ST,NASHVILLE,TN,PT OF LOT 5 EDGEHILL EST. SEC. 66,"YATES, W G & SONS CONSTRUCTION CO",CACT,CAF14R102,Finish out levels P-4. POC MATT GOWER 704-926-...,19.0,37019500,-86.782195,36.151085,21,37203,-9660549.761,4321430.418
23,2021078546,Building Commercial - Tenant Finish Out,Hotel / Motel,9314056500,12/8/2021,8/29/2023,6026512,920 DIVISION ST,NASHVILLE,TN,PT OF LOT 5 EDGEHILL EST. SEC. 66,"YATES, W G & SONS CONSTRUCTION CO",CACT,CAF14R102,To finish out levels 5-8. POC MATT GOWER 704-...,19.0,37019500,-86.782195,36.151085,23,37203,-9660549.761,4321430.418
24,2021078550,Building Commercial - Tenant Finish Out,Hotel / Motel,9314056500,12/8/2021,8/29/2023,3824872,920 DIVISION ST,NASHVILLE,TN,PT OF LOT 5 EDGEHILL EST. SEC. 66,"YATES, W G & SONS CONSTRUCTION CO",CACT,CAF14R102,To finish out Level 9 - roof. POC MATT GOWER ...,19.0,37019500,-86.782195,36.151085,24,37203,-9660549.761,4321430.418

In [16]:
violation_df.head()

,object_id,request_#,date_received,property_apn,property_address,city,state,property_owner,complaint_source,reported_problem,status,cncl_dist,last_activity_date,Last_Activity,last_act__result,violations_noted,longitude,latitude,zipcode,subtype_description,x,y
0,34755,26-1464307,2/10/2026,200001400,133 EAST END RD,GOODLETTSVILLE,TN,"DOWLEN, AUDREY ANN & MARK",HUB,Type: Property Violations - Junk and Debris D...,DONE,10,2026-03-20,Violation Inspection - PS,Violation Resolved,"OPEN STORAGE, JUNK, TRASH, DEBRIS",-86.761063,36.394502,37072,Codes Housing Request,-86.761063,36.394502
1,27518,25-1444564,7/29/2025,300004400,2443 TINNIN RD,GOODLETTSVILLE,TN,"BRATTEN, SANDRA BYRD",HUB,Type: Property Violations - Junk and Debris D...,DONE,10,2025-08-29,Violation Inspection - PS,Violation Resolved,"OPEN STORAGE, JUNK, TRASH, DEBRIS",-86.742112,36.393263,37072,Codes Housing Request,-86.742112,36.393263
2,10827,24-1392290,6/7/2024,400000700,8414 WHITES CREEK PIKE,JOELTON,TN,"HUGHES, SANDRA & PORTER, ROBERT LEE",HUB,Type: Property Violations - Junk and Debris D...,DONE,1,2024-06-26,Violation Inspection - PS,Violation Resolved,"EXTERIOR PROP AREA – FENCE MATERIAL MAIN,OPEN ...",-86.895032,36.382633,37080,Codes Housing Request,-86.895032,36.382633
3,11011,24-1392887,6/11/2024,400000700,8414 WHITES CREEK PIKE,JOELTON,TN,"HUGHES, SANDRA & PORTER, ROBERT LEE",INSPECTOR REPORTED,HIGH GRASS/WEEDS,DONE,1,2024-06-26,Violation Inspection - PS,Violation Resolved,HIGH WEEDS,-86.895032,36.382633,37080,Codes Housing Request,-86.895032,36.382633
4,34006,25-1458100,12/2/2025,400000800,8480 WHITES CREEK PIKE,JOELTON,TN,"LARES, MIGUEL",HUB-SPC,Occupant has erected a fence with black screen...,DONE,1,2026-02-09,Violation Inspection - PS,Violation Resolved,"BUILDING AND ZONING PERMIT REQUIRED,PARKING ON...",-86.896914,36.386063,37080,Codes Housing Request,-86.896914,36.386063

In [17]:
permits_df.isna().sum()

Permit_#                       0
Permit_type_description        0
Permit_subtype_description     0
Parcel                         0
Date_entered                   0
Date_issued                    0
Construction_cost              0
Address                        0
City                           2
State                          0
Subdivision_lot                0
Contact                        1
Permit_type                    0
Permit_sub_type                0
Purpose                        0
Council_district              15
Census_tract                   0
Longitude                      0
Latitude                       0
ObjectId                       0
Zipcode                        0
x                              0
y                              0
dtype: int64

In [18]:
violation_df.isna().sum()

object_id               0
request_#               0
date_received           0
property_apn            0
property_address        0
city                    3
state                   0
property_owner          0
complaint_source        0
reported_problem        0
status                  0
cncl_dist               0
last_activity_date      7
Last_Activity           7
last_act__result        7
violations_noted       49
longitude               0
latitude                0
zipcode                 0
subtype_description     0
x                       0
y                       0
dtype: int64

In [27]:
permits_df['Permit_type_description'].value_counts()

Permit_type_description
Building Residential - New                  10326
Building Commercial - Rehab                  3755
Building Residential - Addition              3124
Building Residential - Rehab                 2352
Building Sign Permit                         2157
Building Demolition Permit                   2153
Building Commercial - Tenant Finish Out      1257
Building Commercial - New                     849
Building Residential - Change Contractor      413
Building Use & Occupancy                      393
Building Tree Removal Permit                  347
Building Commercial - Roofing / Siding        346
Building Commercial - Addition                252
Building Commercial - Change Contractor       182
Building Residential - Roofing / Siding       166
Building Commercial - Shell                   136
Building Commercial - Amend Permit            100
Building Residential - Amend Permit            67
Building Commercial - Foundation               50
Building Residential Rehab Storm Damage        47
Building Commercial - Fire Damage              38
Building Residential - Fire Damage             36
Building Commercial - Structural Frame         23
Building Residential New Storm Damage          21
Building Commercial Rehab Storm Damage         11
Building Residential - Foundation               7
Building Demolition Storm Damage                7
Building Commercial New Storm Damage            4
Building Moving Permit                          3
Name: count, dtype: int64

In [28]:
violation_df['subtype_description'].value_counts()

subtype_description
Codes Housing Request                   27206
Codes High Grass and Weeds               7923
PS Audit                                 3803
Short Term Rental Property               1519
CA Codes Case                             893
Codes Sign Request                        697
Home Occupation PS Complaint              289
Codes Right of Way Request                156
CA Paid Parking Lot                       114
CA PS Night Inspection                     48
Codes Neighborhood Request                 19
Codes Urban Forestry                       16
Landlord Registration Violation            16
CA Paid Parking Garage                      6
PS - Sign Removal                           6
Codes Building Division                     3
Health Department General Sanitation        1
Codes Vacant Lot High Grass                 1
Name: count, dtype: int64

In [29]:
permits_df.head()

,Permit_#,Permit_type_description,Permit_subtype_description,Parcel,Date_entered,Date_issued,Construction_cost,Address,City,State,Subdivision_lot,Contact,Permit_type,Permit_sub_type,Purpose,Council_district,Census_tract,Longitude,Latitude,ObjectId,Zipcode,x,y
0,2020037584,Building Commercial - Rehab,Day Care Center (Up To 75) - Child Care,5106006200,6/17/2020,4/9/2024,82455,1022 S GRAYCROFT AVE,MADISON,TN,LOT 1 DUE WEST TOWERS DAY CARE,TANDEM CONSTRUCTION LLC,CACR,CAB03I402,parcel is zoned RM9 and RS20 and contains 11.1...,3.0,37010802,-86.736233,36.252179,1,37115,-9655433.269,4335376.492
1,2020062603,Building Use & Occupancy,"Multifamily, Townhome",4315005700,10/5/2020,7/24/2023,1,910 OLD HICKORY BLVD E,MADISON,TN,LOT 60 SEC 2 A RAINBOW TERRACE,JARRATT BUILDERS LLC,CAUO,CAA03R301,MASTER PERMIT ONLY… … NO CONSTRUCTION… …OLD HI...,9.0,37010602,-86.689794,36.262452,2,37115,-9650263.708,4336794.677
2,2020077789,Building Commercial - New,Restaurant (Take Out),7102009200,12/14/2020,9/26/2023,409214,2505 BRICK CHURCH PIKE,NASHVILLE,TN,E SIDE BRICK CH PK N OF BROOKLYN AVE,VIVID1 BUILDERS LLC,CACN,CAF31A203,retail market with take out food 1 story with ...,2.0,37012701,-86.778860,36.212955,3,37207,-9660178.492,4329963.316
3,2021020545,Building Commercial - New,"Community Education, Indr Tennis Court",13114010000,4/6/2021,11/7/2023,1,1313 HILDRETH DR,NASHVILLE,TN,LOT 316 & 317 SEC 8 SEVEN HILLS,Seven Hill Club,CACN,CAC03A313,Use permit to erect a bubble over existing ten...,34.0,37018602,-86.813901,36.082376,4,37215,-9664079.235,4311962.049
4,2021023674,Building Commercial - New,"Leasing / Sales Office, Other",16400033500,4/18/2021,1/30/2024,10000,110 WATERSTONE WAY 1412,ANTIOCH,TN,LOT 2 3300 MURFREESBORO PIKE,CIP CONSTRUCTION COMPANY,CACN,CAD03B000,To construct a 50 sf mail kiosk for Cascades A...,8.0,37015631,-86.618345,36.060232,6,37013,-9642310.087,4308912.433

In [35]:
resi_df = permits_df[permits_df['Permit_type_description'].str.contains('Residential', case=False, na=False)]
resi_df.head(10)

,Permit_#,Permit_type_description,Permit_subtype_description,Parcel,Date_entered,Date_issued,Construction_cost,Address,City,State,Subdivision_lot,Contact,Permit_type,Permit_sub_type,Purpose,Council_district,Census_tract,Longitude,Latitude,ObjectId,Zipcode,x,y
5,T2021027879,Building Residential - New,"Accessory Structure, Pools - Residential",13004001000,5/4/2021,4/7/2026,1638305,4024 B SUNNYBROOK DR,NASHVILLE,TN,LOT 18 PT 17 ROYAL OAKS,WIECK CONSTRUCTION LLC,CARN,CAA14U017,"Addition of a new Pool House, Patios and swimm...",34.0,37017902,-86.842535,36.098825,28617,37205,-9667266.791,4314228.085
6,2021035334,Building Residential - New,Single Family Residence,160080C00700CO,6/6/2021,8/28/2025,406275,5412 TROUSDALE DR,NASHVILLE,TN,LOT 7 BRENTWOOD BRANCH,RAD DEVELOPMENT INC,CARN,CAA01R301,new build - residence 3351 H&C square feet....,26.0,37018801,-86.757758,36.050057,5,37220,-9657829.434,4307511.344
12,2021047790,Building Residential - New,Detached Accessory Dwelling Unit,11704025400,7/28/2021,11/30/2023,450000,2804 B OAKLAND AVE,NASHVILLE,TN,LOT 33 BELMONT TERRACE,LAYTON HOMES 2 LLC,CARN,CAA11R301,RECEIVED DETACHED DWELLING COVENANT 20210813-0...,18.0,37016900,-86.795751,36.122052,12,37212,-9662058.795,4317428.549
18,2021065100,Building Residential - New,Single Family Residence,160080C00500CO,10/11/2021,2/23/2024,425272,5421 TROUSDALE DR,NASHVILLE,TN,LOT 5 BRENTWOOD BRANCH,RAD DEVELOPMENT INC,CARN,CAA01R301,TO CONSTRUCT SINGLE FAMILY RESIDENCE WITH 3234...,26.0,37018801,-86.757718,36.049594,18,37220,-9657825.020,4307447.550
19,2021068296,Building Residential - New,"Accessory Structure, Pools - Residential",062110B01600CO,10/25/2021,9/7/2023,92000,2707 B PENNINGTON BEND RD,NASHVILLE,TN,LOT 16 THE SUMMIT AT PENNINGTON BEND CHASE,BACKYARD LIVING LLC,CARN,CAA14U017,TO INSTALL 14’X22’ INGROUND POOL TO REAR OF EX...,15.0,37015300,-86.688073,36.224199,19,37214,-9650072.153,4331514.823
26,2021080120,Building Residential - Addition,Single Family Residence,8313002400,12/14/2021,10/7/2024,254604,1204 RUSSELL ST,NASHVILLE,TN,LOT 63 E EDGEFIELD ADDN,"HURTADO, DAFNE",CARA,CAA01R301,TO CONSTRUCT 2100 SQFT ADDITION OFF REAR OF EX...,6.0,37019200,-86.748344,36.174916,26,37206,-9656781.487,4324716.298
27,2021081541,Building Residential - New,Detached Accessory Dwelling Unit,8313002400,12/20/2021,4/22/2024,94942,1204 C RUSSELL ST,NASHVILLE,TN,LOT 63 E EDGEFIELD ADDN,CONCORDIA DEVELOPMENT INC,CARN,CAA11R301,TO CONSTRUCT DETACHED ACCESSORY DWELLING UNIT ...,6.0,37019200,-86.748366,36.174769,27,37206,-9656783.905,4324696.031
28,2022002416,Building Residential - New,Single Family Residence,6911006800,1/12/2022,11/27/2023,220657,3910 HYDES FERRY RD,NASHVILLE,TN,S/S ASHLAND CITY HY-N/S OLD HYDES FERRY PK,"JACKSON BUILDERS,LLC",CARN,CAA01R301,To construct a single family residence with 17...,1.0,37012802,-86.844794,36.198606,28,37218,-9667518.297,4327983.790
29,2022005717,Building Residential - New,Single Family Residence,081031Y00200CO,1/26/2022,9/19/2024,300563,2409 18TH AVE N,NASHVILLE,TN,UNIT B 18TH AVENUE HOMES,BUILD TRUST HOMES LLC,CARN,CAA01R301,To construct a new HPR single-family residence...,2.0,37013700,-86.812448,36.190737,29,37208,-9663917.520,4326898.362
31,2022008466,Building Residential - New,Single Family Residence,034060C00100CO,2/8/2022,7/24/2023,160027,211 CUDE LN,MADISON,TN,UNIT A 211 CUDE LANE TOWNHOMES,T & S INVESTMENT CO,CARN,CAA01R301,TO CONSTRUCT UNIT OF PROPOSED HORIZONTAL PROPE...,10.0,37010401,-86.692787,36.295683,31,37115,-9650596.919,4341383.478

In [36]:
com_df = permits_df[permits_df['Permit_type_description'].str.contains('Commercial', case=False, na=False)]
com_df.head(10)

,Permit_#,Permit_type_description,Permit_subtype_description,Parcel,Date_entered,Date_issued,Construction_cost,Address,City,State,Subdivision_lot,Contact,Permit_type,Permit_sub_type,Purpose,Council_district,Census_tract,Longitude,Latitude,ObjectId,Zipcode,x,y
0,2020037584,Building Commercial - Rehab,Day Care Center (Up To 75) - Child Care,5106006200,6/17/2020,4/9/2024,82455,1022 S GRAYCROFT AVE,MADISON,TN,LOT 1 DUE WEST TOWERS DAY CARE,TANDEM CONSTRUCTION LLC,CACR,CAB03I402,parcel is zoned RM9 and RS20 and contains 11.1...,3.0,37010802,-86.736233,36.252179,1,37115,-9655433.269,4335376.492
2,2020077789,Building Commercial - New,Restaurant (Take Out),7102009200,12/14/2020,9/26/2023,409214,2505 BRICK CHURCH PIKE,NASHVILLE,TN,E SIDE BRICK CH PK N OF BROOKLYN AVE,VIVID1 BUILDERS LLC,CACN,CAF31A203,retail market with take out food 1 story with ...,2.0,37012701,-86.778860,36.212955,3,37207,-9660178.492,4329963.316
3,2021020545,Building Commercial - New,"Community Education, Indr Tennis Court",13114010000,4/6/2021,11/7/2023,1,1313 HILDRETH DR,NASHVILLE,TN,LOT 316 & 317 SEC 8 SEVEN HILLS,Seven Hill Club,CACN,CAC03A313,Use permit to erect a bubble over existing ten...,34.0,37018602,-86.813901,36.082376,4,37215,-9664079.235,4311962.049
4,2021023674,Building Commercial - New,"Leasing / Sales Office, Other",16400033500,4/18/2021,1/30/2024,10000,110 WATERSTONE WAY 1412,ANTIOCH,TN,LOT 2 3300 MURFREESBORO PIKE,CIP CONSTRUCTION COMPANY,CACN,CAD03B000,To construct a 50 sf mail kiosk for Cascades A...,8.0,37015631,-86.618345,36.060232,6,37013,-9642310.087,4308912.433
8,2021037636,Building Commercial - Tenant Finish Out,"Multifamily, Apt / Twnhome > 5 Unit Bldg",105071C00100CO,6/15/2021,9/15/2023,40000,624 MERRITT ST 101,NASHVILLE,TN,UNIT 4 THE FINERY MASTER CONDOMINIUM AMENDED,ARCHER WESTERN CONSTRUCTION LLC,CACT,CAA03R399,BUILDING PERMIT #2: FLEX SPACE within THE FINE...,17.0,37016100,-86.770966,36.140038,8,37203,-9659299.727,4319907.562
9,2021038553,Building Commercial - Tenant Finish Out,"Multifamily, Apt / Twnhome > 5 Unit Bldg",105071C00100CO,6/18/2021,9/15/2023,40000,620 MERRITT AVE 101,NASHVILLE,TN,UNIT 4 THE FINERY MASTER CONDOMINIUM AMENDED,ARCHER WESTERN CONSTRUCTION LLC,CACT,CAA03R399,BUILDING PERMIT #6: FLEX SPACE WHITE BOX with...,17.0,37016100,-86.770210,36.139994,9,37203,-9659215.545,4319901.429
10,2021038554,Building Commercial - Tenant Finish Out,"Multifamily, Apt / Twnhome > 5 Unit Bldg",105071C00100CO,6/18/2021,10/6/2023,40000,475 GRAY ST,NASHVILLE,TN,UNIT 4 THE FINERY MASTER CONDOMINIUM AMENDED,ARCHER WESTERN CONSTRUCTION LLC,CACT,CAA03R399,BUILDING PERMIT #25: Flex Space North WHITE BO...,17.0,37016100,-86.770199,36.141129,10,37203,-9659214.378,4320057.923
13,2021049445,Building Commercial - New,Recycling Facility,4303001000,8/4/2021,4/8/2024,1057200,928 MYATT INDUSTRIAL DR,MADISON,TN,LOT 10 RIVERGATE INDUSTRIAL PARK,Dave Purser,CACN,CAK05H000,"Construct an approx. 10,700 sqft engineered me...",9.0,37010401,-86.688659,36.280431,13,37115,-9650137.406,4339277.182
16,2021061942,Building Commercial - Shell,"Multifamily, Townhome",9212046900,9/27/2021,1/9/2025,80212214,1717 HAYES ST,NASHVILLE,TN,PT OF LOT 72-77 BOYD HOME TRACT,JUSTIN CRANDALL,CACH,CAA03R301,This is a Core & Shell permit package for a hi...,19.0,37019500,-86.796363,36.154097,16,37203,-9662126.966,4321845.628
17,2021063222,Building Commercial - New,"Fuel Storage, Hazardous (H1-H5)",9209017700,10/1/2021,2/21/2024,7500000,416 38TH AVE N,NASHVILLE,TN,LOTS 22 TH 25 & 42 TH 45 W. R. WILSON,PAULO FONDA,CACN,CAH03H000,Construction of a new 2.5 million gallon groun...,24.0,37013500,-86.829826,36.153903,17,37209,-9665852.028,4321818.852

In [ ]:
res_df = permits_df[permits_df['Permit_type_description'].str.contains('Residential', case=False, na=False)]
res_df.head(10)